Typography control update, removed lazysize, sidebar position issue in woocommerce archive page
- Added: Typography options for body and headings.
- Updated: WPCS maintained.
- Fixed: Missing `=` after an instance of `value` attribute in an `input` tag in `value"' . get_search_query() . '"`.
- Fixed: PHP error - `PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function get_day_link(), 1 passed in /breadcrumbs.php on line 802 and exactly 3 expected.`
- Fixed: Sidebar position issue in WooCommerce archive pages.
- Fixed: Other minor fixes.
- Removed: Everest backup plugin recommendation.
- Removed: Lazysize jQuery plugin.